/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */
import { VideoEvaluation } from '../services/evaluationService.agentHub';
import { VeoModel, AspectRatio, Resolution, SpeechType } from '../types';
import { GenerationMetadata } from './story-creation';

export type ProjectType = 'movie' | 'short' | 'commercial';

export interface GenerationSettings {
  model: VeoModel;
  aspectRatio: AspectRatio;
  resolution: Resolution;
  isLooping: boolean;
  camera_movement?: 'static/fixed' | 'dynamic' | string; // Camera movement preference
}

export interface SceneAssetAttachment {
  assetId: string;
  url?: string; // Direct URL to asset (for storyboard frames from story storage)
  role: 'character' | 'background' | 'prop' | 'storyboard-frame'; // Role of asset in the scene
  order: number; // Display/reference order (0-based)
}

export type SceneType = 'shot' | 'transition';

export interface Scene {
  id: string;
  sceneType?: SceneType; // 'shot' (default) or 'transition' - transitions use first-last-frame generation
  title: string;
  duration: number;
  prompt: string; // Visual description for video generation
  cameraAngle: string;
  direction?: string; // Acting/scene direction guidelines (shown in UI)

  // Speech/Dialogue
  voiceover?: string; // The spoken text (dialogue or narration)
  speechType?: SpeechType; // 'voiceover' = character speaking on-screen, 'narration' = off-screen narrator

  // Storyboard data (generated by storyboard-designer agent)
  imagePrompt?: string; // AI-generated image prompt used for storyboard frame
  storyboardMood?: string; // Mood/atmosphere from storyboard analysis

  // Audio generation
  audioUrl?: string; // Generated TTS audio file URL
  audioBlob?: Blob; // Temporary audio blob (not persisted)

  // Asset attachments
  attachedAssets?: SceneAssetAttachment[]; // Assets used in this scene

  // Rendering data
  generated: boolean;
  videoUrl?: string;
  videoBlob?: Blob;
  settings?: GenerationSettings;
  firstFrameUrl?: string; // First frame of video - stored as file (e.g., /frames/{projectId}/{sceneId}-first.png)
  lastFrameUrl?: string; // For shot continuity - stored as file (e.g., /frames/{projectId}/{sceneId}-last.png)
  firstFrameDataUrl?: string; // DEPRECATED: Use firstFrameUrl instead (legacy base64 data)
  lastFrameDataUrl?: string; // DEPRECATED: Use lastFrameUrl instead (legacy base64 data)
  referenceMode?: 'previous' | number; // 'previous' = use previous shot, number = use specific ref (1-based)

  // End frame selection for video generation
  endFrameMode?: 'none' | 'asset' | 'next-shot'; // How to select end frame (default: 'none')
  endFrameAssetIndex?: number; // If endFrameMode is 'asset', which asset index to use (1-based, same as referenceMode)
  endFrameUrl?: string; // URL to end frame image (from asset or next shot's first frame)

  // Timeline trimming (for frame extraction control)
  startTrim?: number; // Start trim point in seconds (default: 0)
  endTrim?: number; // End trim point in seconds (default: scene.duration)

  // Evaluation data
  evaluation?: VideoEvaluation;
}

export interface Project {
  id: string;
  title: string;
  description: string;
  type: ProjectType;
  character?: string;

  // Director Persona
  personaId?: string; // Director persona ID (e.g., 'pulp-visionary', 'time-architect')

  // Project-level generation settings
  aspectRatio: AspectRatio; // Applied to all scenes in project
  defaultModel: VeoModel; // Default for new scenes
  defaultResolution: Resolution; // Default for new scenes

  createdAt: number;
  updatedAt: number;
  scenes: Scene[];

  // Generation metadata (optional, for AI-generated stories)
  generationMetadata?: GenerationMetadata;

  // Track story storage assets that have been explicitly deleted by user
  // Stores filenames (e.g., "character-ref-design-1762267856949.png")
  // to prevent auto-sync from re-importing them
  deletedStoryStorageAssets?: string[];
}
